# Generated by Django 3.0.7 on 2020-08-04 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='display_file',
            name='email',
            field=models.CharField(default='cuffg@etown.edu', max_length=200),
            preserve_default=False,
        ),
    ]
