# Generated by Django 3.0.7 on 2020-08-04 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blockchain', '0002_display_file_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='display_file',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
